import './css/3_style.css'
import './css/4_style.css'
import './css/5_style.css'
import './css/7_style.css'
import './css/8_style.css'
import './css/9_style.css'
import './css/10_style.css'
import './css/13_style.css'
import './css/16_style.css'
import './css/17_style.css'
import './css/22_style.css'
// import './1.Props_Children'
// import './2.Props_Custom_Events'
// import './3_Badge_Component'
// import './1.controlledComponentsAndRefs/4_Counter_input_field_1'
// import './1.controlledComponentsAndRefs/5_Counter_textarea_field_2_exercise';
// import './1.controlledComponentsAndRefs/6_UseState_component_advance'
// import './1.controlledComponentsAndRefs/7_UseRef_Hook_Input'
// import './1.controlledComponentsAndRefs/8_UseRef_ForwardRef_Hook_Input'
// import './1.controlledComponentsAndRefs/9_ToggleAbleForm'
// import './2.reducers/10_Reducers_1'
// import './2.reducers/11_Custom_UseState_By_UseReducer'
// import './2.reducers/12_Custom_Hooks_with_Use_Reducer';
// import './2.reducers/13_Char_Sheet_App_UseState'
// import './2.reducers/14_Char_Sheet_App_UseReducer'
// import './2.reducers/15_Char_Sheet_App_UseReducer_By_CustomHooks'
// import './2.reducers/16_Promise_based_state_machine'
// import './3.compoundComponents/17_A_Single_Data_Entry_Point'
// import './3.compoundComponents/18_A_Single_Data_Entry_Point_reordering_element'
// import './3.compoundComponents/19_A_Single_Data_Entry_Point_adding_disable_property'
// import './3.compoundComponents/20_Replacing_Props_With_Compound_Component'
// import './3.compoundComponents/21_Context_API_With_Compound_Component'
import './3.compoundComponents/22_Date_Picker_Compound_Component'