import './css/3_style.css'
import './css/4_style.css'
import './css/5_style.css'
import './css/7_style.css'
import './css/8_style.css'
import './css/9_style.css'
import './css/10_style.css'
import './css/13_style.css'
import './css/16_style.css'
// import './1.Props_Children'
// import './2.Props_Custom_Events'
// import './3_Badge_Component'
// import './controlledComponentsAndRefs/4_Counter_input_field_1'
// import './controlledComponentsAndRefs/5_Counter_textarea_field_2_exercise';
// import './controlledComponentsAndRefs/6_UseState_component_advance'
// import './controlledComponentsAndRefs/7_UseRef_Hook_Input'
// import './controlledComponentsAndRefs/8_UseRef_ForwardRef_Hook_Input'
// import './controlledComponentsAndRefs/9_ToggleAbleForm'
// import './reducers/10_Reducers_1'
// import './reducers/11_Custom_UseState_By_UseReducer'
// import './reducers/12_Custom_Hooks_with_Use_Reducer';
// import './reducers/13_Char_Sheet_App_UseState'
// import './reducers/14_Char_Sheet_App_UseReducer'
// import './reducers/15_Char_Sheet_App_UseReducer_By_CustomHooks'
import './reducers/16_Promise_based_state_machine'